### ISSUE TITLE
Fix typo in 108

### ISSUE THREAD

**Issue by manminusone** [MediaWiki-Bot/MediaWiki-Bot#110]
In the process of fixing issue 108 a typo was introduced in line 39 of t/25-sitematrix.t: an "r" was appended to an undef value to make "undefr".

**Comment by manminusone** [comment]
PR is here: https://github.com/MediaWiki-Bot/MediaWiki-Bot/pull/111

**Comment by wp-seth** [comment]
oops, my fault, https://github.com/MediaWiki-Bot/MediaWiki-Bot/commit/65399e343140a9b65ea2e2c6e19109d711aa1222

thanks for your help! :-)
