### ISSUE TITLE
Documentation improvement: add an "overview" section for context 

### ISSUE THREAD

**Issue by fhocutt** [MediaWiki-Bot/MediaWiki-Bot#62]
The documentation is good if you know exactly what you are looking for, but doesn't offer a new user context to see where all of the details fit together. It would help to add an "overview" section to the documentation describing MediaWiki::Bot's overall design, intended purpose, and the types of functions it makes available

**Comment by wp-seth** [comment]
at least i'll try to re-order and group the functions. i guess that should help a lot already.

**Comment by wp-seth** [comment]
idea of new order/structure:
- SYNOPSIS
- DESCRIPTION
- METHODS
  - Initialization
    - new
    - set_wiki
    - login
      - Single User Login
      - Basic authentication
      - Bot passwords
    - logout
  - Getting information about pages
    - diff
    - get_history
    - get_history_step_by_step (new function similar to get_history, but RAM-friendly)
    - get_links_to_page (old name: what_links_here)
    - get_page (new function similar to get_text, but improved token handling)
    - get_page_id (old name: get_id)
    - get_pages
    - get_pages_by_prefix (old name: prefixindex)
    - get_protection
    - get_recent_revision (fusion of recent_edit_to_page and get_last; will return user, timestamp, and id; exclude_user is an additional param)
    - get_recent_users (old name: get_users)
    - get_text
    - <s>is_protected</s> (was marked as deprecated, successor is get_protection)
  - Modifying pages
    - edit
    - CAPTCHAs
    - move
    - patrol
    - purge_page
    - revert
    - undo
  - Files / Images
    - get_image
    - get_image_usage (old name: image_usage)
    - get_global_image_usage (old name: global_image_usage)
    - <s>links_to_image</s> (was marked as deprecated, successor is get_image_usage)
    - test_image_exists
    - upload (will be able to upload from url)
    - <s>upload_from_url</s> (will be merged into upload function)
  - Recent changes
    - <s>update_rc</s> (was marked as deprecated, successor is get_recent_changes)
    - get_recent_changes (old name: recentchanges)
  - Users
    - count_contributions
    - <s>timed_count_contributions</s> (will be merged into count_contributions)
    - get_all_users (old name: get_allusers)
    - get_contributions (old name: contributions)
    - get_recent_actions (fusion of top_edits and last_active; will return more than just timestamp; limit will be a param)
    - get_usergroups (old name: usergroups)
    - is_blocked
    - <s>test_blocked</s> (was marked as deprecated, successor is is_blocked)
    - is_g_blocked
    - was_blocked
    - <s>test_block_hist</s> (was marked as deprecated, successor is was_blocked)
    - was_g_blocked
    - was_locked
  - Categories
    - get_pages_in_category
    - <s>get_all_pages_in_category</s> (will be merged into get_pages_in_category)
    - get_all_categories
  - Namespaces
    - get_namespace_names
    - get_pages_in_namespace
  - Templates and Transclusions
    - expand_templates (old name: expandtemplates)
    - get_transclusions (old name: list_transclusions)
  - External links
    - get_external_links (old name: linksearch)
  - Meta
    - db_to_domain
    - domain_to_db
    - get_log
    - search
  - Mail
    - email
  - Options hashref
- ERROR HANDLING

i know that this would destroy backward-compatibility, but it would make the naming more consistent and thus less error-prone and easier for mw-beginners.

**Comment by wp-seth** [comment]
this issue is used for the re-ordering part only. it should be completely backward-compatible, because the functions won't be changed.

the renaming and parameter changes (both of which are breaking changes) will be done in #102
