### ISSUE TITLE
Add option to use older API for _get_edittoken

### ISSUE THREAD

**Issue by coax75ohm** [MediaWiki-Bot/MediaWiki-Bot#71]
Wikia uses an older API version and fails on the edit function because it is unable to get the edit token. Reverting the _get_edittoken portion of 6afb1edae64ab2f7806b2c0964e3fc59e10a5fab fixes this. Please make this an option.

**Comment by doherty** [comment]
Supporting legacy versions of MediaWiki is really not something I'm keen on doing. We've always targeted WMF wikis, which have historically tended to be quite up-to-date.

If there is a clear signal in whatever version information the API exposes, I would consider accepting a pull request that fetched a CSRF token in the appropriate way for the version of MediaWiki we're talking to.

**Comment by wp-seth** [comment]
i guess, we are not able to support mediawikis that are ~7 years old.
so i'll close this as "wontfix".
