### ISSUE TITLE
t/48-get_image.t fails

### ISSUE THREAD

**Issue by eserte** [MediaWiki-Bot/MediaWiki-Bot#72]
t/48-get_image.t fails approximately since December 2014. See http://analysis.cpantesters.org/reports_by_field?SUBMIT_xxx=Submit&distv=MediaWiki-Bot-5.006002&field=qr%3A%28Failed+test\s%2B\S%2B.*%29&field=meta%3Adate&field=qr%3A%28Failed+test\s%2B\S%2B.*%29
The only pass reports are where Imager is not installed and this test is skipped.

**Comment by doherty** [comment]
Thanks for the report. It turns out I had already fixed this back in January, but haven't done a release since then. I'll see if I can fix that this weekend.

**Comment by doherty** [comment]
Fixed in 6edf32af102f3c8048f88cc0fbd55c16afc65789
