### ISSUE TITLE
t/18-is_blocked.t Failed test 'current blocks'

### ISSUE THREAD

**Issue by cnam78** [MediaWiki-Bot/MediaWiki-Bot#73]
I tried to install MediaWiki::Bot module with cpanp on Ubuntu 12.04. I've received several error messages, one is this message:
```
t/18-is_blocked.t .............. 4/6 
#   Failed test 'current blocks'
#   at t/18-is_blocked.t line 38.
# Looks like you failed 1 test of 6.
t/18-is_blocked.t .............. Dubious, test returned 1 (wstat 256, 0x100)
```
In the test file, this line : 
`my $result = $bot->is_blocked('User:Hiwhispees');`
`$result` variable is empty, it seems that this user account is blocked. Which account must be seet to get right test ?

Regards

**Comment by doherty** [comment]
Fixed in 75858da291cd4f54bab2d7fd965fb658b55e5ace
