### ISSUE TITLE
Package for Debian

### ISSUE THREAD

**Issue by scfc** [MediaWiki-Bot/MediaWiki-Bot#75]
I have filed a [Request for Package](https://bugs.debian.org/786800) to include MediaWiki::Bot in Debian to replace our local package in Wikimedia Tools.  Any help is appreciated.

**Comment by doherty** [comment]
> We believe that the bug you reported is fixed in the latest version of
libmediawiki-bot-perl, which is due to be installed in the Debian FTP archive.

In general, however, CPAN is the only target I plan to package for.
