### ISSUE TITLE
cpanm install fails on debian stable jessie

### ISSUE THREAD

**Issue by sbts** [MediaWiki-Bot/MediaWiki-Bot#76]
When installing using
cpanm MediaWiki::Bot
the install fails with quite a few errors.
Some of which are probably only issues with the tests themselves.

See attached log file.
[build.txt](https://github.com/MediaWiki-Bot/MediaWiki-Bot/files/47908/build.txt)

**Comment by doherty** [comment]
Thanks for the report. Unfortunately, I already know that some of the tests
that are currently failing are not just bugs in the test suite.

I don't spend much time on this any longer, so I encourage you to either
ignore the test failures and accept that the code is buggy and/or out of
sync with MediaWiki, or fix them yourself. I do have the time and
willingness to review patches and do releases.

-Mike

**Comment by doherty** [comment]
All tests should be passing in the latest release.
