### ISSUE TITLE
Support for "bot passwords"

### ISSUE THREAD

**Issue by guiwp** [MediaWiki-Bot/MediaWiki-Bot#80]
As of 1.27, the **login action should only be used in combination with bot passwords** [...]

Related: #77 

What about creating another parameter for the constructor ($botpass?):
Ex.:
```
my $bot = MediaWiki::Bot->new({
        assert      => 'bot',
        host        => 'de.wikimedia.org',
        login_data  => { username => "Mike's bot account", password => "password", botpass=> 1 },
});
```

If the login type is _botpass_, after the login process we could strip the the suffix username**@botname** from the username string, otherwise MediaWiki::Bot::_is_loggedin will complain.

**Comment by doherty** [comment]
Thanks for your troubleshooting on this. Your suggestion sounds fine. Do
you want to write the patch for the fix and tests?

**Comment by guiwp** [comment]
@doherty I've to thank you for this amazing library ;)

I'd be happy if I could submit a patch now, but unfortunately I'm learning Perl for just some weeks (~2h/day with distractions hehe), I can't produce code following coding conventions, even git I'm learning now.

But from my little guesses I could see something like:

[Bot.pm#L433](https://github.com/MediaWiki-Bot/MediaWiki-Bot/blob/master/lib/MediaWiki/Bot.pm#L433)

```
$username =~ s{@\w+}{} if $self->{botpass}; # remove @word from username
$self->{username} = $username;
```

**Comment by guiwp** [comment]
I'm learning how to test Perl code but I'm not getting success...

I've tried `PWPPasswod=... PWPUsername=... EXTENDED_TESTING=1 prove -Ilib t/02-login.t` but it says:
```
t/02-login.t .. skipped: I can't log in without credentials
Files=1, Tests=0,  1 wallclock secs ( 0.03 usr  0.00 sys +  0.13 cusr  0.01 csys =  0.17 CPU)
Result: NOTESTS
```

But I'm sure I've passed the both username and password through env variables...

**Comment by doherty** [comment]
I have a series of patches to fix this and other test failures. I should be
able to get a new release out in the next couple days

**Comment by guiwp** [comment]
Thank you @doherty . I think that not just me but a lot of people (folks of #77 too!) that use your library will be happy to known this.

Keep up the good work man! Maybe some years ahead I can contribute with code in to your project, but right now it's impossible for my little skills. 

Again, thank you very much.  I'd like to learn (old boy) Perl and with your library things become more interesting because I have tasks to do on Wikipedia, Wikibooks (some times its just simple data mining, etc.) .
