### ISSUE TITLE
Login token handling not working

### ISSUE THREAD

**Issue by AppleBottom** [MediaWiki-Bot/MediaWiki-Bot#83]
I'm trying to use this framework to write a bot for a non-Wikimedia wiki[1], but I cannot log in to the wiki.

API logins require a login token[2]. The ->login() method currently tries to obtain a token by calling api.php?action=query&meta=tokens&type=login, but this is not supported anymore and instead yields the following result.

`
{"warnings":{"main":{"*":"Unrecognized parameter: 'type'"},"query":{"*":"Unrecognized value for parameter 'meta': tokens"}}}
`

The proper way to log in nowadays, as per [2], is to do two POST requests to api.php?action=login. Using only lgname and lgpassword will make Mediawiki return the necessary login token that can then be used in the second attempt to actually log in.

I understand that this module is unmaintained, and that keeping up with MediaWiki's ever-changing API is frustrating. That said I'd like to point out that the new login method is apparently handled by MediaWiki::API (which this module uses), so the fix should be relatively straightforward: if logging in fails, attempt to use $self->{api}->login() as a fallback method, and only give up if that fails as well.

This would be a minor change, but it would make a big difference for me (and likely others). I'd owe you several beers if you could go ahead and implement it. :)

Thanks!

1. http://conwaylife.com/wiki
2. https://www.mediawiki.org/wiki/Manual:Creating_a_bot#Logging_in

**Comment by doherty** [comment]
I'm afraid I can't keep up with the breaking changes in the MediaWiki API,
so this software is now unmaintained. If you'd like to submit patches, I
can do code review, merging, and releases -- but I'm not going to be doing
any development work in the foreseeable future.

**Comment by AppleBottom** [comment]
OK, thanks for letting me know.

I'll see what I can do about submitting a patch/pull request -- no promises, however!

**Comment by wp-seth** [comment]
i guess, this has been fixed in MediaWiki::API in 2020, see https://metacpan.org/dist/MediaWiki-API/changes
