### ISSUE TITLE
usercontribs module of the Api no longer accepts usernames that are prefixed with User:

### ISSUE THREAD

**Issue by hawkeye-7** [MediaWiki-Bot/MediaWiki-Bot#84]
As reported on wiki, the usercontribs module of the Api no longer accepts usernames that are prefixed with User:, which is a breaking change, that caused the MediaWiki-Bot to break.

https://phabricator.wikimedia.org/T194916

I have a patch below, which strips the 'User:' instead of adding it.

```diff
index 1a54326..b0fd8c8 100644
--- a/lib/MediaWiki/Bot.pm
+++ b/lib/MediaWiki/Bot.pm
@@ -2368,7 +2368,7 @@ B<References:> L<API:Usercontribs|https://www.mediawiki.org/wiki/API:Usercontrib
 sub last_active {
     my $self     = shift;
     my $username = shift;
-    $username = "User:$username" unless $username =~ /User:/i;
+    $username =~ s/^User://i;
     my $res = $self->{api}->list({
             action  => 'query',
             list    => 'usercontribs',
```

**Comment by wp-seth** [comment]
it seems that currently both is supported (with or without "user:" prefix).

so i would just delete that line but don't _force_ the removal of "user:".
